Readme is using the wrong repo name when trying to add chart with helm
eidolon-ai/base-agent-machine pull request #21
Opened 2024-09-10 16:08 UTC by jrgleason

see changes

2024-09-10 16:26 UTC, dbrewster requested changes

2024-09-10 16:26 UTC, dbrewster commented on .gitignore
> +*.iml
We want the iml files checked in, no?

2024-09-10 17:58 UTC, LukeLalor commented on .gitignore
> +*.iml
no, people using these repos may not be using IntelliJ. If folks use this as a template who are using IJ, they can just remove it from .gitignore.

That said, *.iml was already in .gitignore, so this change is a duplicate that we should remove

2024-09-14 00:56 UTC, closed without merging

2024-09-14 00:56 UTC, jrgleason commented
see https://github.com/eidolon-ai/agent-machine/pull/22