Allowing magic for people not running locally
eidolon-ai/base-agent-machine pull request #22
Opened 2024-09-14 00:56 UTC by jrgleason

This provides a few make commands and some docs to make deploying to non-local examples easier.

2024-09-14 00:57 UTC, jrgleason commented
@LukeLalor Is eidolon an ok default namespace. I don't think it is good to use the default.

2024-09-17 16:25 UTC, LukeLalor requested changes
Mostly works for me with with colima.

We need to update the get_service_url scripts, but everything else seems to be working 👍

2024-09-17 16:25 UTC, LukeLalor commented on Makefile
> +DOCKER_REPO_NAME := $(if $(DOCKER_REPO_URL),$(DOCKER_REPO_URL),my-eidolon-project)
Do we need to redefining this? can we use DOCKER_REPO_NAME ?= my-eidolon-project to set the default?

2024-09-17 16:25 UTC, LukeLalor commented on Makefile
> +	@echo "WebUI is running at $$(./k8s/get_service_url.sh eidolon-webui-service --namespace=$(NAMESPACE))"
This did not work for me

2024-09-17 16:25 UTC, LukeLalor commented on Makefile
> +	@echo "WebUI is running at $$(./k8s/get_service_url.sh eidolon-webui-service --namespace=$(NAMESPACE))"
```
------------------------------------------------------------------
Error from server (NotFound): services "eidolon-ext-service" not found
Server is running at Error: Couldn't find NodePort for 'eidolon-ext-service'. Make sure the service exists and is of type NodePort.
Error from server (NotFound): services "eidolon-webui-service" not found
WebUI is running at Error: Couldn't find NodePort for 'eidolon-webui-service'. Make sure the service exists and is of type NodePort.
------------------------------------------------------------------
```

2024-09-17 18:23 UTC, jrgleason commented on Makefile
> +	@echo "WebUI is running at $$(./k8s/get_service_url.sh eidolon-webui-service --namespace=$(NAMESPACE))"
Interesting could you tell why it failed? Adding the namespace is something that can be removed I just didn't like using the default namespace.

2024-09-17 18:25 UTC, jrgleason commented on Makefile
> +DOCKER_REPO_NAME := $(if $(DOCKER_REPO_URL),$(DOCKER_REPO_URL),my-eidolon-project)
It does default this is the repo url in case it isn't local

2024-09-18 02:49 UTC, LukeLalor commented on Makefile
> +	@echo "WebUI is running at $$(./k8s/get_service_url.sh eidolon-webui-service --namespace=$(NAMESPACE))"
I don't think the bash script accepts the --namespace argument. I didn't debug it beyond the log statement above

2024-09-19 00:34 UTC, jrgleason commented on Makefile
> +	@echo "WebUI is running at $$(./k8s/get_service_url.sh eidolon-webui-service --namespace=$(NAMESPACE))"
@LukeLalor Can we work together to get this to work with the namespaces? I think there is just some issue maybe with it already being installed. Lets walk through it and see what the issue is.

2024-09-19 06:13 UTC, LukeLalor approved these changes

2024-09-20 02:14 UTC, merged